### PR TITLE
Fix xatrix intro image

### PR DESCRIPTION
**Pull request by 0lvin**
Scale image if initiall image has different dimention or aspects

### CODE REVIEW

**Comment by 0lvin** [comment]
@Yamagi Could you please provide rights for review and merge PR? Thank you.

**Comment by Yamagi** [comment]
@0lvin I've send you and invite to join the 'ref_vk' team. That should you give full access to the ref_vk repo.

**Comment by 0lvin** [comment]
@Yamagi Thank you.

**Comment by 0lvin** [comment]
@Spirrwell @rg3 Could you please review?

Currently any raw image render reuse texture created on first call, and if image size have used first time, all next images will be scale down to small.  Maybe better recreate bigger buffer if new image is bigger.

**Comment by Spirrwell** [comment]
I'll take a look more closely in a bit. Is this related to issue #7 here?

**Comment by 0lvin** [comment]
@Spirrwell I have not reproduced #7 for now.

**Comment by Spirrwell** [comment]
This actually does fix issue #7 for me whether you intended or not.

Instead of scaling this way, you could call QVk_ReleaseTexture() (after making a declaration for it) and just do

```
if (vk_rawTexture_width != cols || vk_rawTexture_height != rows)
{
	QVk_ReleaseTexture(&vk_rawTexture);
}
```

That isn't ideal because that incurs a vkDeviceWaitIdle(), but unless EVERY single cinematic image is a different size, that shouldn't really matter too much performance-wise.

The most "correct" way would be to have some kind of deletion queue that the texture gets pushed to and delete it when it's safe to do so. I don't know if there's already a way to do this built into ref_vk or not.

**Comment by 0lvin** [comment]
@Spirrwell Thank you.

I have changed code to recreate texture in case of different size. vk_validation=2 does not show any errors, it looks like no obvious issues.

**Comment by 0lvin** [comment]
@Yamagi @Spirrwell @DanielGibson @rg3 Could you please review and merge?

**Comment by Spirrwell** [comment]
I see it's still the same, and it's one of the ideas I suggested. So no problems here.

**Comment by Yamagi** [comment]
Oh, I thought you would merge this yourself. Since everyone is happy: Merged!

**Comment by 0lvin** [comment]
Thank you,

> Oh, I thought you would merge this yourself.

By some reason github decided to not show "merge" button for me in PR. Let's recheck when we have new PR.

**Comment by Yamagi** [comment]
I think you had the wrong permission level. I've upgraded you to *write*, let's see if that is sufficient.

**Pull request merged**
